# Generated by Django 5.2.8 on 2025-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='recommended_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
