# Generated by Django 5.2.8 on 2025-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_score_recommended_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
