# Generated by Django 5.2.8 on 2025-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='created_at',
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (for applicant only)'), ('SUBMITTED', 'Submitted to recruiter'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
